language: python

python:
    - "2.7"
cache: pip
install:
  - pip install -r requirements.txt

addons:
  browserstack:
    username: "mukeshtiwari"
    access_key:
      secure: "Oi5Pk0P8OAi21w7bg+GIWZWqV/V9RII/D7yfP5ROTuE+RhQY4P6O3+ApYmnIz1XOoe7PYvLladqBTbmYNj5BRas12Ato3NvYEl3y915mDeIKSKRp9ur2ZgqndO4qjfSr3DfgAGQunvS0M5W0dnUJLhfoc60d17N8sWIOsRixNqqw6EAXxsvTlUvjXGqawzLN3KJvj7loIZr+2dksSaF1ulFDCSFAsO2KoUBYb8edU2bNJ1gqNCp9BqzuP9bgRCQhVqaGyUtoBv2s5VP0/3nqZqhOoAT5dg49iK8wuHvmcSeCjo2Ci+baV9QBr/d+Q716Nb89RDKFxO/pUXkgON6ge/YeurO9lCZNpvT0cWK4lbzsqDh+GHSVt9RbXl6cOJTerfwJcyITNLgv1uiTb2w7sOL0Tty93O3EnJHOY9VrljSF75ha5Pi29FkhKRX2Q4dckFUjBupF4ICt7dj882jyN0W/bfRhC+4Zrmxi4fIMFgLrdT09Qs5ggRH7tHE0/v7XWxBCsg9BBzAQsPBJqT5N+wyghKgLYZxk+U9Tvh4n57bwt50FjvsiUf1pQP7fc36yBHl9PBBNFZI2HByjwYzc2tbusX08PEA7wrui52yh/R7SgZryuwaLWQmHkmK6EBjMkGsNotf+juyzquyOn7WxM/Pp/LVDLDQNy/mxmfJruU0="

script:
  - paver run browserstack
